### ISSUE TITLE
File Load Is Invalid

### ISSUE THREAD

**Issue by ar0711** [chuongmep/NavisAddinManager#2]
When loading the plugin into Navisworks I keep getting the error 'File Load is Invalid'. Even with the sample code provided (Hello World). Is there a better explanation of the error or any idea what could be wrong?

Using Navisworks Manage 2022 and Visual Studio 2022

**Comment by chuongmep** [comment]
Hi @ar0711 , many thanks fof your raise issue , I guess you are build with difference version. Did you check correct configuration version 2022 before build project ?

**Comment by chuongmep** [comment]
This issue don't have any new response, so I will view it as a resolved.
